Controllers/FilmController.cs
using ASPcinema.Domains;
using ASPcinema.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPcinema.Controllers
{
    public class FilmController : Controller
    {
        protected readonly ModelCinemaContainer _db;
        // GET: Film

        public FilmController()
        {
            _db = new ModelCinemaContainer();
        }

        public ActionResult List()
        {

            var model = new SessionsPageModel()
            {
                Films = _db.FilmSet.AsEnumerable().ToList(),
                FilmSessions = _db.FilmSessionSet.AsEnumerable().ToList()
            };
            return View(model);
        }

        public ActionResult Sessions()
        {

            var model = new SessionsPageModel()
            {
                Films = _db.FilmSet.AsEnumerable().ToList(),
                FilmSessions = _db.FilmSessionSet.AsEnumerable().ToList()
            };
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var film = _db
                .FilmSet
                .FirstOrDefault(p => p.FilmID == id);

            if (film == null)
            {
                return View("NotFound");
            }

            var filmlol = _db.FilmSet.Where(f => f.FilmID == id).FirstOrDefault();
            var fslol = _db.FilmSessionSet.Where(f => f.Film.FilmID == filmlol.FilmID).AsEnumerable().ToList();


            List<SeatTicket> seatslol = new List<SeatTicket>();

            foreach (var item in fslol)
            {
                seatslol.AddRange(_db.SeatTicketSet.Where(t => t.FilmSession.FilmSessionID == item.FilmSessionID).AsEnumerable().ToList());
            }

            var model = new DetailsPageModel()
            {
                Film = filmlol,
                FilmSessions = fslol,
                Tickets = seatslol
            };

            return View(model);
        }

        public ActionResult Buy(int filmID, int sessionID)
        {
            var filmlol = _db.FilmSet.Where(f => f.FilmID == filmID).FirstOrDefault();
            var fslol = _db.FilmSessionSet.Where(f => f.FilmSessionID == sessionID).FirstOrDefault();


            List<SeatTicket> seatslol = new List<SeatTicket>();


            seatslol.AddRange(_db.SeatTicketSet.Where(t => t.FilmSession.FilmSessionID == fslol.FilmSessionID).AsEnumerable().ToList());


            var model = new BuyPageModel()
            {
                Film = filmlol,
                FilmSession = fslol,
                Tickets = seatslol,
                SelectedSeats = ""
            };

            return View(model);
        }

        public ActionResult Purchased(BuyPageModel model1)
        {
            var filmlol = _db.FilmSet.Where(f => f.FilmID ==
            model1.Film.FilmID).FirstOrDefault();

            var fslol = _db.FilmSessionSet.Where(f => f.FilmSessionID ==
            model1.FilmSession.FilmSessionID).FirstOrDefault();

            string[] selectedSeatsIDS = model1.SelectedSeats.Split(' ');
            selectedSeatsIDS = selectedSeatsIDS.Where(s => s != "").ToArray();

            List<Seat> seatslol = new List<Seat>();

            foreach (var item in selectedSeatsIDS)
            {
                int number = int.Parse(item);
                seatslol.Add(_db.SeatSet.Where(s => s.CinemaHall.CinemaHallID == fslol.CinemaHall.CinemaHallID).
                    Where(s => s.SeatNumber == number).FirstOrDefault());
                number = 3;
            }

            foreach (var item in seatslol)
            {
                var ticket = item.SeatTicket.Where(t => t.FilmSession.FilmSessionID ==
                model1.FilmSession.FilmSessionID).FirstOrDefault();
                ticket.Bought = true;
                _db.SaveChanges();
            }



            var model2 = new PurchaseViewModel()
            {
                Film = filmlol,
                FilmSession = fslol,
                SelectedSeats = seatslol
            };

            return View(model2);
        }

        public ActionResult Edit(int filmID)
        {
            var model = new EditPageModel()
            {
                Film = _db.FilmSet.Where(f => f.FilmID == filmID).FirstOrDefault(),
                Genres = _db.GenreSet.AsEnumerable().ToList(),
                AgeRatings = _db.AgeRatingSet.AsEnumerable().ToList(),
                SelectedAgeRating = null,
                SelectedGenre = null

            };

            return View(model);
        }

        public ActionResult Edited(EditPageModel model1)
        {
            var editedFilm = model1.Film;
            editedFilm.AgeRating = _db.AgeRatingSet.Where(r => r.Title == model1.SelectedAgeRating).FirstOrDefault();
            editedFilm.Genre = _db.GenreSet.Where(r => r.Title == model1.SelectedGenre).FirstOrDefault();


            var uneditedFilm = _db.FilmSet.Where(t => t.FilmID == editedFilm.FilmID).FirstOrDefault();

            #region params

            uneditedFilm.Title = editedFilm.Title;
            uneditedFilm.Country = editedFilm.Country;
            uneditedFilm.TimeLength = editedFilm.TimeLength;
            uneditedFilm.ImagePath = editedFilm.ImagePath;
            uneditedFilm.Description = editedFilm.Description;
            uneditedFilm.MoreGenres = editedFilm.MoreGenres;
            uneditedFilm.Actors = editedFilm.Actors;
            uneditedFilm.Producer = editedFilm.Producer;
            uneditedFilm.KinopoiskLink = editedFilm.KinopoiskLink;

            uneditedFilm.Genre = editedFilm.Genre;
            uneditedFilm.AgeRating = editedFilm.AgeRating;

            #endregion


            _db.SaveChanges();



            var model = new SessionsPageModel()
            {
                Films = _db.FilmSet.AsEnumerable().ToList(),
                FilmSessions = _db.FilmSessionSet.AsEnumerable().ToList()
            };

            return View("Sessions", model);
        }

        public ActionResult Add()
        {
            var model = new AddPageModel()
            {
                Film = new Film(),
                Genres = _db.GenreSet.AsEnumerable().ToList(),
                AgeRatings = _db.AgeRatingSet.AsEnumerable().ToList(),
                SelectedAgeRating = null,
                SelectedGenre = null
            };


            return View(model);
        }

        public ActionResult Added(AddPageModel model1)
        {
            var addedFilm = model1.Film;
            addedFilm.AgeRating = _db.AgeRatingSet.Where(r => r.Title == model1.SelectedAgeRating).FirstOrDefault();
            addedFilm.Genre = _db.GenreSet.Where(r => r.Title == model1.SelectedGenre).FirstOrDefault();
            addedFilm.ImagePath = "32ds";

            _db.FilmSet.Add(addedFilm);
            _db.SaveChanges();


            var model = new SessionsPageModel()
            {
                Films = _db.FilmSet.AsEnumerable().ToList(),
                FilmSessions = _db.FilmSessionSet.AsEnumerable().ToList()
            };

            return View("Sessions", model);
        }

        public ActionResult Delete(int filmID)
        {
            
            _db.FilmSet.Remove(_db.FilmSet.Where(f => f.FilmID == filmID).FirstOrDefault());
            _db.SaveChanges();

            var model = new SessionsPageModel()
            {
                Films = _db.FilmSet.AsEnumerable().ToList(),
                FilmSessions = _db.FilmSessionSet.AsEnumerable().ToList()
            };

            return View("Sessions", model);
        }
    }

}

Views/Film/Add.cshtml
@model ASPcinema.Models.AddPageModel

<div>
    <div class="panel-body">
        @using (Html.BeginForm("Added", "Film", FormMethod.Post, new { style = "margin-top: 5px;" }))
        {
            
            <div class="row">
                <!--<div class="col-lg-2 col-sm-6">
                    <img src="~/Content/" width="150" />
                    <button type="submit" class="btn btn-danger pull-right" style="margin-top: 10px;">
                        Изменить постер
                    </button>
                </div>-->
                <div class="col-lg-2 col-sm-6">
                    <div class="col-md-10">
                        <img id="ShowImage" width="150" src="~/Content/sample.jpg" style="border: solid 1px;"/>
                        <input id="FileUpload" type="file" accept="image/jpeg" style="margin-top: 10px;" />
                    </div>
                </div>


                <div class="col-lg-10 col-sm-6">
                    <div class="title1"><span>Название фильма:</span></div>
                    <div id="EditTextBoxTitle">@Html.TextAreaFor(m => m.Film.Title)</div>
                </div>
                <div class="col-lg-10 col-sm-6" id="DetailsDescription">
                    <div class="title1"><span>Описание:</span></div>
                    <div id="EditTextBoxDescription">@Html.TextAreaFor(m => m.Film.Description)</div>
                </div>
            </div>
            <div class="col-lg-10 col-sm-6" id="DetailsDescription">
                <div class="info-group clear">
                    <div class="title1"><span>Страна:</span></div>
                    <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.Country)</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>Режиссер:</span></div>
                    <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.Producer)</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>Длительность:</span></div>
                    <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.TimeLength)</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>В главных ролях:</span></div>
                    <div id="EditTextBoxRoles">@Html.TextAreaFor(m => m.Film.Actors)</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>Основной жанр:</span></div>
                    <div id="dropDownBox">@Html.DropDownListFor(m => m.SelectedGenre, new SelectList(Model.Genres.Select(c => c.Title).ToList()))</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>Все жанры:</span></div>
                    <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.MoreGenres)</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>Ссылка на kinopoisk:</span></div>
                    <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.KinopoiskLink)</div>
                </div>
                <div class="info-group clear">
                    <div class="title1"><span>Возрастной рейтинг:</span></div>
                    <div id="dropDownBox">@Html.DropDownListFor(m => m.SelectedAgeRating, new SelectList(Model.AgeRatings.Select(c => c.Title).ToList()))</div>
                </div>

                <div class="info-group clear">



                    <button type="submit" class="btn btn-success pull-right">
                        Сохранить изменения
                        <span class="glyphicon glyphicon-edit"></span>
                    </button>



                </div>

            </div>
        }

    </div>
</div>

Views/Film/Buy.cshtml
@model ASPcinema.Models.BuyPageModel

<div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-10 col-sm-6" id="FilmTitle">
                @Html.ActionLink(Model.Film.Title.Split(',').First(),
         "Details",
         new
         {
             @id = Model.Film.FilmID
         })
            </div>
            <div class="col-lg-10 col-sm-6" id="FilmCinemaHallInfo">
                <text>@Html.DisplayFor(model => model.FilmSession.CinemaHall.Title), </text>
                <text>@Html.DisplayFor(model => model.FilmSession.SessionDateTime)</text><br />

            </div>

            <div class="col-lg-10 col-sm-6" id="sessionButtons">
                @foreach (var item in Model.Film.FilmSession.Distinct().OrderBy(d => d.SessionDateTime))
                {
                    if (item.CinemaHall.CinemaHallID == Model.FilmSession.CinemaHall.CinemaHallID &
                        item.SessionDateTime == Model.FilmSession.SessionDateTime)
                    {
                        <div class="btnBuyActive">
                            <a href="/Film/Buy?filmID=@Model.Film.FilmID&sessionID=@item.FilmSessionID">
                                <span class="sessionTime">@item.SessionDateTime.TimeOfDay.ToString().Substring(0, 5)</span>
                                <span class="price">@item.SesstionTickets.ElementAt(0).Price ₽</span>
                                <span class="hall">@item.CinemaHall.Title</span>
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="btnBuy">
                            <a href="/Film/Buy?filmID=@Model.Film.FilmID&sessionID=@item.FilmSessionID">
                                <span class="sessionTime">@item.SessionDateTime.TimeOfDay.ToString().Substring(0, 5)</span>
                                <span class="price">@item.SesstionTickets.ElementAt(0).Price ₽</span>
                                <span class="hall">@item.CinemaHall.Title</span>
                            </a>
                        </div>
                    }
                }
            </div>


        </div>
        <div>

        </div>
        <div id="selectionAndPurchase" style="display: flex;">
            <div id="cinemaHallSelection">
                <div id="explanationBlock" style="align-items: center;">
                    <div class="btnSeat"></div>
                    <text style="height: 20px;">ᅠместо свободноᅠ</text>
                    <div class="btnSeatOccupied"></div>
                    <text style="height: 20px;">ᅠместо занятоᅠ</text>
                    <div class="btnSeat" style="background: mediumvioletred;"></div>
                    <text style="height: 20px;">ᅠваш выборᅠ</text>
                </div>
                <div id="cinemaScreen">
                    <text>Экран</text>
                </div>
                <div class="s" id="seatButtons">
                    @foreach (var item in Model.Tickets)
                    {
                        if (item.Seat.SeatTicket.Where(t => t.FilmSession.FilmSessionID == 
                        Model.FilmSession.FilmSessionID).FirstOrDefault().Bought == false)
                        {
                            <div class="btnSeat" >
                                <a>
                                    <span class="btnSeat_id" onclick="submitButtonStyle(this)" 
                                    style="min-height: 30px; min-width: 30px; display: flex; 
                                    justify-content: center; align-items: center; border-radius: 5px;">@item.Seat.SeatNumber</span>
                                </a>
                            </div>
                        }
                        else
                        {
                            <div class="btnSeatOccupied">
                                <a href="">
                                    <span class="btnSeat_id">@item.Seat.SeatNumber</span>
                                </a>
                            </div>

                        }
                    }
                </div>
            </div>
        </div>
        <div id="TicketsCalculationAndPurchase"
        style="font-size: 20px; display: flex; margin-top: 15px;
        margin-left: 5px; margin-right: 5px; width: 430px;">

            <text id="selectedSeatsText" style="white-space: nowrap;">Выбранные места:</text>
            @using (Html.BeginForm("Purchased", "Film", FormMethod.Post, new { style = " display: flex; margin-left: 5px; margin-right: 5px;" }))
            {
                @Html.HiddenFor(model => model.Film.FilmID);
                @Html.HiddenFor(model => model.FilmSession.FilmSessionID);
                @Html.TextAreaFor(model => model.SelectedSeats, new { id = "selectedSeats", style = "border: transparent; width:100px; resize: none; height: 100px; font-size: 18px;" })
                
                <input type="submit" value="Купить за 0₽" id="buttonBuyTickets" disabled="disabled" style="width: 150px; font-size: 16px; height: 40px;"/>
        
                
            }
            <text id="price"></text>

        </div>

            <!--<div id="explanationBlock" style="align-items: center;">
    <div class="btnSeat"></div>
    <text>ᅠместо свободноᅠ</text>
    <div class="btnSeatOccupied"></div>
    <text>ᅠместо занятоᅠ</text>
    <div class="btnSeat" style="background: mediumvioletred;"></div>
    <text>ᅠваш выборᅠ</text>
    </div>-->
        
            <script>
                let exactPrice = 0;

                function submitButtonStyle(_this) {

                    if (document.getElementById('selectedSeats').innerHTML == "") {
                        const btn = document.getElementById('buttonBuyTickets');
                        btn.disabled = false;

                    }
                    if (_this.style.background == "mediumvioletred") {
                        _this.style.background = "#0079b4";
                        document.getElementById('selectedSeats').value = document.getElementById('selectedSeats').value.replace(_this.innerHTML, '');
                        document.getElementById('selectedSeats').value = document.getElementById('selectedSeats').value.replace(' ', '');

                        const btn = document.getElementById('buttonBuyTickets');
                        exactPrice = exactPrice - 200;
                        btn.value = "Купить за " + exactPrice + "₽";

                        if (document.getElementById('selectedSeats').value == "") {
                            const btn = document.getElementById('buttonBuyTickets');
                            btn.disabled = true;
                        }

                    }
                    else {
                        _this.style.background = "mediumvioletred";
                        document.getElementById('selectedSeats').value += " " + _this.innerHTML;
                        const btn = document.getElementById('buttonBuyTickets');
                        btn.disabled = false;
                        exactPrice = exactPrice + 200;
                        btn.value = "Купить за " + exactPrice + "₽";
                        
                    }
                }
            </script>
        </div>
</div>

Views/Film/Details.cshtml
@model ASPcinema.Models.DetailsPageModel

<div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2 col-sm-6">
                <img src="~/Content/@Html.DisplayFor(model => model.Film.ImagePath)" width="150" />
            </div>
            <div class="col-lg-10 col-sm-6" id="FilmTitleAndEditBtn">
                <div id="FilmTitle">
                    @Html.DisplayFor(model => model.Film.Title)
                </div>
                <div id="FilmEditBtn">
                    @if (User.IsInRole("admin"))
                    {
                        using (Html.BeginForm("Edit", "Film",
                            new
                            {
                                @filmId = Model.Film.FilmID,
                            }))
                        {
                            <div class="col-lg-10 col-sm-6">
                                <button type="submit" class="btn btn-warning pull-right">
                                    Изменить фильм
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>
                            </div>
                        }
                    }
                </div>
            </div>
            <div class="col-lg-10 col-sm-6" id="DetailsDescription">
                <text>
                    @if (Model.Film.Description == "")
                    {
                        <text>Нет подробного описания.</text>
                    }
                    else
                    {
                        @Html.DisplayFor(model => model.Film.Description);
                    }

                </text>
            </div>
            <div class="col-lg-10 col-sm-6" id="sessionsToday">
                <text>Сеансы на сегодня, @DateTime.UtcNow.ToString("dd.MM.yyyy")</text>
            </div>
            <div class="col-lg-10 col-sm-6" id="sessionButtons">
                @foreach (var item in Model.FilmSessions.Distinct()
                            .OrderBy(d => d.SessionDateTime))
                {
                    <div class="btnBuy">
                        <a href="/Film/Buy?filmID=@Model.Film.FilmID&sessionID=@item.FilmSessionID">
                            <span class="sessionTime">@item.SessionDateTime.TimeOfDay.ToString().Substring(0, 5)</span>
                            <span class="price">@item.SesstionTickets.ElementAt(0).Price ₽</span>
                            <span class="hall">@item.CinemaHall.Title</span>
                        </a>
                    </div>
                }

            </div>

        </div>


        <div class="col-lg-10 col-sm-6" id="DetailsDescription">
            <div class="info-group clear">
                <div class="title1"><span>Страна:</span></div>
                <div class="value"><span>@Html.DisplayFor(model => model.Film.Country)</span></div>
            </div>
            <div class="info-group clear">
                <div class="title1"><span>Режиссер:</span></div>
                <div class="value"><span>@Html.DisplayFor(model => model.Film.Producer) </span></div>
            </div>
            <div class="info-group clear">
                <div class="title1"><span>Длительность:</span></div>
                <div class="value"><span>@Html.DisplayFor(model => model.Film.TimeLength) </span></div>
            </div>
            <div class="info-group clear">
                <div class="title1"><span>В главных ролях:</span></div>
                <div class="value"><span>@Html.DisplayFor(model => model.Film.Actors) </span></div>
            </div>
            <div class="info-group clear">
                <div class="title1"><span>Жанр:</span></div>
                <div class="value"><span>@Html.DisplayFor(model => model.Film.MoreGenres)</span></div>
            </div>
        </div>
    </div>
</div>

Views/Film/Edit.cshtml
@model ASPcinema.Models.EditPageModel

    <div>
        <div class="panel-body">
            @using (Html.BeginForm("Edited", "Film", FormMethod.Post, new { style = "margin-top: 5px;" }))
            {
                @Html.HiddenFor(model => model.Film.FilmID)
                @Html.HiddenFor(model => model.Film.ImagePath)
                @Html.HiddenFor(model => model.Film.FilmSession)
            <div class="row">
                            <!--<div class="col-lg-2 col-sm-6">
                    <img src="~/Content/" width="150" />
                    <button type="submit" class="btn btn-danger pull-right" style="margin-top: 10px;">
                        Изменить постер
                    </button>
                </div>-->
                <div class="col-lg-2 col-sm-6">
                    <div class="col-md-10">
                        <img id="ShowImage" width="150" src="~/Content/@Model.Film.ImagePath" />
                        <input id="FileUpload"type="file" accept="image/jpeg" style="margin-top: 10px;"/>
                    </div>
                </div>


                <div class="col-lg-10 col-sm-6">
                    <div class="title1"><span>Название фильма:</span></div>
                    <div id="EditTextBoxTitle">@Html.TextAreaFor(m => m.Film.Title)</div>
                </div>
                <div class="col-lg-10 col-sm-6" id="DetailsDescription">
                    <div class="title1"><span>Описание:</span></div>
                    <div id="EditTextBoxDescription">@Html.TextAreaFor(m => m.Film.Description)</div>
                </div>
            </div>
                <div class="col-lg-10 col-sm-6" id="DetailsDescription">
                    <div class="info-group clear">
                        <div class="title1"><span>Страна:</span></div>
                        <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.Country)</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>Режиссер:</span></div>
                        <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.Producer)</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>Длительность:</span></div>
                        <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.TimeLength)</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>В главных ролях:</span></div>
                        <div id="EditTextBoxRoles">@Html.TextAreaFor(m => m.Film.Actors)</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>Основной жанр:</span></div>
                        <div id="dropDownBox">@Html.DropDownListFor(m => m.SelectedGenre, new SelectList(Model.Genres.Select(c => c.Title).ToList()))</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>Все жанры:</span></div>
                        <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.MoreGenres)</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>Ссылка на kinopoisk:</span></div>
                        <div id="EditTextBox">@Html.TextBoxFor(m => m.Film.KinopoiskLink)</div>
                    </div>
                    <div class="info-group clear">
                        <div class="title1"><span>Возрастной рейтинг:</span></div>
                        <div id="dropDownBox">@Html.DropDownListFor(m => m.SelectedAgeRating, new SelectList(Model.AgeRatings.Select(c => c.Title).ToList()))</div>
                    </div>

                    <div class="info-group clear">



                        <button type="submit" class="btn btn-success pull-right">
                            Сохранить изменения
                            <span class="glyphicon glyphicon-edit"></span>
                        </button>



                    </div>

                </div>
            }

        </div>
    </div>

Views/Film/List.cshtml
@model ASPcinema.Models.SessionsPageModel


<h2>@ViewBag.Title</h2>
@section Scripts
{
    <link href="~/Content/style1.css" rel="stylesheet" />
}

@foreach (var item in Model.Films)
{
    <a href="Details/@item.FilmID"><img src="~/Content/@item.ImagePath" width="150" onclick="" /></a>

}

Views/Film/Purchased.cshtml
@model ASPcinema.Models.PurchaseViewModel

    <div>
        <div class="panel-body">
            <div class="row">
                <div>
                    <div id="FilmTitleAndEditBtn">
                        <div id="FilmTitle">
                            Поздравляем! Вы купили билеты на фильм  "@Html.DisplayFor(model => model.Film.Title)"
                        </div>
                    </div>
                    <div style="color: grey; font-size: 16px;">
                        <text> @Model.FilmSession.CinemaHall.Title,</text>
                        <text>@Model.FilmSession.SessionDateTime,</text>
                        @if (Model.SelectedSeats.Count == 1)
                        {
                            <span>место</span>
                        }
                        else
                        {
                            <span>места</span>
                        }
                        @foreach (var item in Model.SelectedSeats)
                        {
                            <span>@item.SeatNumber</span>
                        }
                    </div>
                    <div style="font-size: 16px; margin-top: 10px;">
                        Вот ваши цифровые билеты:
                    </div>

                    @foreach (var item in Model.SelectedSeats)
                    {
                        <div id="lol" style="border: 2px solid; width: 360px; margin-top: 20px; display: flex;">
                            <div style=" width:320px; padding: 10px;
background: linear-gradient(90deg, rgba(51,157,255,1) 0%, rgba(249,249,249,1) 100%);">
                                <div>
                                    <text style="font-size: 22px;">@Model.Film.Title</text>
                                </div>
                                <div style="margin-top: 10px;">
                                    <text>Номер Билета</text><br /><text style="font-size: 18px;">174 412 @item.SeatID</text>
                                    
                                </div>

                                <div style="margin-top: 30px;">
                                    <text>Дата: @DateTime.Now.ToString("yyyy.MM.dd")</text>
                                </div>
                                <div>
                                    <text>Сеанс: @Model.FilmSession.SessionDateTime.ToString("HH:mm")</text>
                                </div>
                                <div>
                                    <text>
                                        Зал №@Model.FilmSession.CinemaHall.CinemaHallID,
                                        Ряд @item.RowNumber,
                                        Место @item.SeatNumber
                                    </text>
                                </div>

                            </div>
                            <div style="background-color: white; width: 50px; padding: 5px; border-left: dotted 1px;">
                                <img id="qrCodeImg" src="~/Content/qrcode.png" style="height: 200px; width:40px;"/>
                            </div>
                        </div>
                    }

                </div>

            </div>
            
        </div>
    </div>




                